### PR TITLE
Fix TBB_BUILD_TESTS option

### PR DESCRIPTION
**Pull request by mishchea**
- If TBB_BUILD_TESTS is set to ON, then actually build the unit test
  binaries. Previously, the binaries' executable targets would be
  defined in CMakeLists.txt, but set to EXCLUDE_FROM_ALL, which would
  cause ctest to fail.
- Prefix all TBB test binaries and test names with tbb_test. Previously,
  very generic-sounding test names and executable target names would be
  created, which is IMO bad behavior in a repository meant to be used as
  a library.
- Clean up some style formatting for consistency in root CMakeLists.txt.

### CODE REVIEW

**Comment by mishchea** [comment]
@wjakob, looks like the Travis CI builds are failing for `master` in the same way.

**Comment by mishchea** [comment]
Rather, the AppVeyor builds.

**Comment by mishchea** [comment]
@wjakob do you have feedback about this PR?

**Comment by wjakob** [comment]
Hi,

I think this generally looks great, but I can (of course) not merge it if the testcases fail on Windows/Debug. Can you look into that?

Best,
Wenzel

**Comment by mishchea** [comment]
The tests are failing in `master` in the same way. I don't believe this PR introduced a regression there.

**Comment by wjakob** [comment]
Interesting -- that had not occurred to me.

**Comment by wjakob** [comment]
(fixed a conflict)

**Pull request merged**
