### PR TITLE
Update to 2020.2

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by wjakob** [comment]
These looks like fantastic improvements, please let me know once this is ready to merge.
One request: can you set the Swig Python extension feature to default-off? Most projects using this repository are C++-based and compile TBB recursively as static or shared library to keep the user from having to deal with the dependency. Including Python here will make the build slower, and potentially more fragile.

**Comment by wjakob** [comment]
I also think that you overwrote some project-specific files when untarring TBB, like our readme.

**Comment by jschueller** [comment]
> I also think that you overwrote some project-specific files when untarring TBB, like our readme.

yes, it's difficult to update version because of that, but it's fixed

**Comment by wjakob** [comment]
If I understood your changes correctly, we are no longer testing 32 vs 64 bit on windows. That would be problematic, we should at least have both for one of the MSVC versions.

**Comment by jschueller** [comment]
> If I understood your changes correctly, we are no longer testing 32 vs 64 bit on windows. That would be problematic, we should at least have both for one of the MSVC versions.

ok, lets build for 64 for vs2017 and vs2019, and 32 for vs2015, its not necessary to have all combinations, appveyor builds are slow enough

**Comment by jschueller** [comment]
> These looks like fantastic improvements, please let me know once this is ready to merge.
> One request: can you set the Swig Python extension feature to default-off? Most projects using this repository are C++-based and compile TBB recursively as static or shared library to keep the user from having to deal with the dependency. Including Python here will make the build slower, and potentially more fragile.

ok

**Comment by jschueller** [comment]
@wjakob I think its ready

**Comment by wjakob** [comment]
Merged, thank you!

**Pull request merged**
