### PR TITLE
Add the directory to the tbb_static target's public include directories which allows other targets linking against tbb_static to #include "tbb/tbb.h" and friends

### PR DESCRIPTION
**Pull request by mishchea**

### CODE REVIEW

**Comment by mishchea** [comment]
Ah, I guess this is not compatible with CMake version 2.8...

**Comment by wjakob** [comment]
It would be possible to bump the CMake minimum version using the following source for .travis.yml: "- kubuntu-backports # cmake 2.8.12".
By the way, why just set the public includes for the static build?

**Comment by mishchea** [comment]
But, are you comfortable increasing the minimum CMake version required to use this repository?

The reason I added it to the static library is that that's where I personally wanted/needed the functionality. If you'd like, I can try to do something similar for the other build targets.

**Comment by wjakob** [comment]
Bumping the minimum cmake version would be fine. If this PR is to be accepted, then it should be done consistently everywhere -- thanks!

**Comment by wjakob** [comment]
ping?

**Comment by mishchea** [comment]
Sorry, I'm neck-deep at work. I will definitely get around to this, but I don't know exactly when. If you prefer, I'm ok with you closing the PR, and I'll reopen when I revisit this.

**Comment by wjakob** [comment]
Ok, just ping this thread and I'll reopen it.

**Pull request closed without merging**
