### PR TITLE
fix segfault running tbb build with gcc 6

### PR DESCRIPTION
**Pull request by dakaufma**

### CODE REVIEW

**Comment by hjmjohnson** [comment]
This seems like a well considered work around for gcc6.

**Comment by wjakob** [comment]
This looks good -- thank you!

**Comment by LogicalKnight** [comment]
Note that upstream uses `-flifetime-dse=1` in the makefiles as opposed to `-fno-lifetime-dse` (which is equivalent to `-flifetime-dse=0`). Not sure if there are any practical differences other than providing the compiler with a few more optimization opportunities in certain situations.

**Comment by wjakob** [comment]
I'm actually a bit confused now. We already have a portion of the makefile that adds
```cmake
if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU" AND UNIX AND NOT APPLE)
   check_cxx_compiler_flag ("-flifetime-dse=1" SUPPORTS_FLIFETIME)
   if (SUPPORTS_FLIFETIME)
     add_definitions(-flifetime-dse=1)
   endif()
endif()
```

Why was this new PR needed? Shall I revert it?

**Comment by wjakob** [comment]
The one thing that strikes me as odd is the `` NOT APPLE`` check, and the fat that the GCC version is not considered. Shall we perhaps rather merge these into one joint test which looks for GCC >= 6.0 on any platform and then sets ``-flifetime-dse=1`` instead of th emore drastic ``-fno-lifetime-dse``?

**Comment by LogicalKnight** [comment]
I noticed that as well and agree, as the Intel Makefiles do the same.

**Comment by wjakob** [comment]
@dakaufma, could you please comment on this?

**Comment by dakaufma** [comment]
My change might be outdated -- we actually made this patch several months ago and I was just recently looking at our diff with master and trying to push changes upstream.

It looks like the version we wrote this patch over doesn't set `-flifetime-dse`, so perhaps this patch isn't needed anymore. I'll check.

**Comment by dakaufma** [comment]
It looks like this patch is no longer necessary; good catch, and thanks for looking into this!

**Comment by wjakob** [comment]
ok, done -- thanks for verifying.

**Pull request merged**
