### PR TITLE
Build some tests

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by wjakob** [comment]
Great, thank you. Is there some cmake-specific issue with the commented ones, or are those commented in the original build system as well?

**Comment by jschueller** [comment]
Some do not build and some fail, nothing related to cmake so far.

**Comment by wjakob** [comment]
Ok, sounds good -- as you are still changing things around, let me know when you think that these are ready to be merged (same for the other PR)

**Comment by jschueller** [comment]
Build should be ok for windows too.

**Comment by jschueller** [comment]
@wjakob any idea how to build my "tests" target on appveyor ? I see ctest is run in the script.

**Comment by wjakob** [comment]
Re: running tests on AppVeyor, this could be good to look at https://github.com/pybind/pybind11/blob/master/.appveyor.yml (it builds and runs a target called 'check')

**Comment by jschueller** [comment]
good to go this time.

**Comment by wjakob** [comment]
Thanks!

**Pull request merged**
