### PR TITLE
Add TBB_SET_SOVERSION option

### LINKED ISSUE #71: shared library name is .so and not .so.2
A problem with velocyto was traced to numba and its interaction with this tbb package.  Details here:

https://github.com/velocyto-team/velocyto.py/issues/269

In short, numba (and possibly others) look for "libtbb.so.2", but the cmake build of this tbb only creates "libtbb.so". Renaming the shared libraries from this build from .so to .so.2, then making links to the .so.2 version from the .so version resolved this issue. Ditto for the other two other shared libraries it made. 

Older libtbb versions, such as those on CentOS 8, all seem to all have that naming convention.

### PR DESCRIPTION
**Pull request by jschueller**
Closes #71

### CODE REVIEW

**Comment by jschueller** [comment]
ping @wjakob

**Comment by wjakob** [comment]
The issue you've pointed out is fairly specific to the setup with Numba and not relevant for the use case of most packages that recursively include this repository (where it is simply easier to have a bunch of plain .so files). Can't you just set SOVERSION yourself from a parent project?

**Comment by jschueller** [comment]
This change is innocuous, and just mimics upstream packages as much as possible.

**Comment by wjakob** [comment]
That is understood -- but the role of this repository is not to mirror upstream, but to package up TBB in a way that makes it convenient to use recursively as a git submodule, within a larger CMake-based build system of a parent project. I'll close this, I don't think it makes sense to include here.

**Comment by jschueller** [comment]
ok that's not the goal of the repo. but if it helps packaging it doesnt hurt to include this one-liner.

**Comment by jschueller** [comment]
would you reconsider, please ?

**Comment by wjakob** [comment]
How about making it an optional feature that is default-off?

Thanks,
Wenzel

**Comment by jschueller** [comment]
yes, why not

**Comment by wjakob** [comment]
How about ``TBB_SET_SOVERSION``?

**Comment by jschueller** [comment]
ok

**Comment by wjakob** [comment]
Merged, thanks!

**Pull request merged**
