### PR TITLE
ENH: Update to TBB 2017 version

### PR DESCRIPTION
**Pull request by hjmjohnson**
The new release TBB is now under a new more
open license.
                                 Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

The list of most significant changes made over time in
Intel(R) Threading Building Blocks (Intel(R) TBB).

Intel TBB 2017
TBB_INTERFACE_VERSION == 9100

Changes (w.r.t. Intel TBB 4.4 Update 5):

- static_partitioner class is now a fully supported feature.
- async_node class is now a fully supported feature.
- Improved dynamic memory allocation replacement on Windows* OS to skip
    DLLs for which replacement cannot be done, instead of aborting.
- Intel TBB no longer performs dynamic memory allocation replacement
    for Microsoft* Visual Studio* 2008.
- For 64-bit platforms, quadrupled the worst-case limit on the amount
    of memory the Intel TBB allocator can handle.
- Added TBB_USE_GLIBCXX_VERSION macro to specify the version of GNU
    libstdc++ when it cannot be properly recognized, e.g. when used
    with Clang on Linux* OS. Inspired by a contribution from David A.
- Added graph/stereo example to demostrate tbb::flow::async_msg.
- Removed a few cases of excessive user data copying in the flow graph.
- Reworked split_node to eliminate unnecessary overheads.
- Added support for C++11 move semantics to the argument of
    tbb::parallel_do_feeder::add() method.
- Added C++11 move constructor and assignment operator to
    tbb::combinable template class.
- Added tbb::this_task_arena::max_concurrency() function and
    max_concurrency() method of class task_arena returning the maximal
    number of threads that can work inside an arena.
- Deprecated tbb::task_arena::current_thread_index() static method;
    use tbb::this_task_arena::current_thread_index() function instead.
- All examples for commercial version of library moved online:
    https://software.intel.com/en-us/product-code-samples. Examples are
    available as a standalone package or as a part of Intel(R) Parallel
    Studio XE or Intel(R) System Studio Online Samples packages.

Changes affecting backward compatibility:

- Renamed following methods and types in async_node class:
    Old                   New
    async_gateway_type => gateway_type
    async_gateway()    => gateway()
    async_try_put()    => try_put()
    async_reserve()    => reserve_wait()
    async_commit()     => release_wait()
- Internal layout of some flow graph nodes has changed; recompilation
    is recommended for all binaries that use the flow graph.

Preview Features:

- Added template class streaming_node to the flow graph API. It allows
    a flow graph to offload computations to other devices through
    streaming or offloading APIs.
- Template class opencl_node reimplemented as a specialization of
    streaming_node that works with OpenCL*.
- Added tbb::this_task_arena::isolate() function to isolate execution
    of a group of tasks or an algorithm from other tasks submitted
    to the scheduler.

Bugs fixed:

- Added a workaround for GCC bug #62258 in std::rethrow_exception()
    to prevent possible problems in case of exception propagation.
- Fixed parallel_scan to provide correct result if the initial value
    of an accumulator is not the operation identity value.
- Fixed a memory corruption in the memory allocator when it meets
    internal limits.
- Fixed the memory allocator on 64-bit platforms to align memory
    to 16 bytes by default for all allocations bigger than 8 bytes.
- As a workaround for crashes in the Intel TBB library compiled with
    GCC 6, added -flifetime-dse=1 to compilation options on Linux* OS.
- Fixed a race in the flow graph implementation.

Open-source contributions integrated:

- Enabling use of C++11 'override' keyword by Raf Schietekat.

------------------------------------------------------------------------

### CODE REVIEW

**Comment by wjakob** [comment]
Hm, interesting -- there is also #16 :) -- both of which are failing atm.

Looks like you deleted some needed cmake build system-related files from the 'build' directory.

Looks like there were some platform compilation flag changes that also need to be transferred from the makefiles to the cmake build system.

**Comment by hjmjohnson** [comment]
@wjakob  I have added the files and now all checks are passing.

I work on several other projects that use CMake (ITK,VTK,vxl), and I am interested in provided a more complete CMake solution for TBB.  Would you be willing accept patches that also generate files that are compatible with "find_package" for other cmake projects that depend on tbb?

I've done some of this type of work for the LAPACK libraries, ITK, VTK, and vxl libraries in the past.

Regards,
Hans

**Comment by LogicalKnight** [comment]
@hjmjohnson Thanks! I'll close my pull request. I for one would love to see a more complete set of CMake scripts. I get by with CMake, but haven't yet mastered it!

**Comment by LogicalKnight** [comment]
Looks like the updated PR also include built products. I assume that wasn't intentional...

**Comment by hjmjohnson** [comment]
@LogicalKnight Build products removed.  Sorry about that.  

@wjakob This is now passing all the nightly tests.  I have some other CMake improvements being prepared in another patch set.

**Comment by wjakob** [comment]
I just untarred https://www.threadingbuildingblocks.org/sites/default/files/software_releases/source/tbb2017_20160722oss_src.tgz on top of this PR and noticed that many files are not identical. How come?

**Comment by hjmjohnson** [comment]
@wajakob.  I thought they would have been.  I used essentially the same process.  Let me try yet again.

**Comment by hjmjohnson** [comment]
@wjakob,  I just untarred the above file over the git repository as well.

There were only two files that had CRLF replaced by LF
	modified:   examples/graph/stereo/msvs/stereo.sln
	modified:   examples/graph/stereo/msvs/stereo.vcxproj

I think that this was due to a filter in my git settings on mac.  I added an did a "git commit -n " to try to avoid those changes, and now there are no differences.

Hans

18:42 $ tar -xzvf ~/Downloads/tbb2017_20160722oss_src.tgz >/dev/null 2>&1
18:42 $ cd tbb2017_20160722oss
18:42 $ git status
On branch tbb2017_20160722oss
Your branch is up-to-date with 'origin/tbb2017_20160722oss'.
nothing to commit, working tree clean

**Comment by wjakob** [comment]
It looks like some files are missing from the distribution, e.g. just checking the ``src`` and ``include`` directories:

```
       	include/tbb/flow_graph_abstractions.h
       	include/tbb/internal/_flow_graph_streaming_node.h
       	src/perf/time_split_node.cpp
       	src/test/harness_preload.h
```

**Comment by wjakob** [comment]
Hi,

sorry, never mind my previous post -- the files match and all of that looks good. However, one more thing: the change notes explicitly mention that some compilation flags were changed (e.g. on Linux) for certain compiler versions. It would make sense to propagate these compilation flags to the CMakeLists.txt build system.

Thanks,
Wenzel

**Comment by hjmjohnson** [comment]
Wenzel,

 

I have a site review the next few days, and I will not be able to propagate those compiler flags.  Is that something that you could do?


Thanks,

Hans

 

 

--

**Comment by hjmjohnson** [comment]
@wjakob This is now passing all tests, and includes the propagation of compiler flags.

**Comment by wjakob** [comment]
merged, thank you!

**Comment by wjakob** [comment]
FYI: you accidentally deleted README.md ;). I also made a few CMake tweaks.

**Pull request merged**
