### PR TITLE
Use target based build flags

### LINKED ISSUE #50: CXX standard // switch to target based build flags
Modifying `CMAKE_CXX_FLAGS` now that this is on cmake 3.x should be removed in favor of target based build flags.  Consider a parent project that is using `CMAKE_CXX_STANDARD`, a very simple example:

```cmake
cmake_minimum_required(VERSION 3.3 FATAL_ERROR)
project(supertest)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
add_subdirectory(tbb)
```

Then when compiling, you will get

```console
$ make VERBOSE=1
...
[  1%] Building CXX object tbb/CMakeFiles/tbb.dir/src/tbb/arena.cpp.o
cd... && /usr/bin/c++ ...  -mrtm -std=c++11... -std=c++14 ... -c /tmp/jaja/tbb/src/tbb/arena.cpp
```

with `-std=c++11` appearing before `-std=c++14`, which I think (but don't know for sure) that the compiler will typically choose the first one it sees and ignore all others.  C++11 and C++14 are mostly compatible but my (not so firm) understanding is that this could be problematic when mixing C++11 and C++17 parent project.

**Edit**: ref: because of this https://github.com/wjakob/tbb/blob/b066defc0229a1e92d7a200eb3fe0f7e35945d95/CMakeLists.txt#L119

The would-be PR would contain two items:

1. Use `CMAKE_CXX_STANDARD` (being careful not to override parent project settings of course!).  Note this will not engage the [cmake compile-features](https://cmake.org/cmake/help/latest/manual/cmake-compile-features.7.html) such as `cxx_std_11`, `CMAKE_CXX_STANDARD` is the best way to allow parent projects to control child-cxx-standards, and the goal of this repo is for convenience of `add_subdirectory` ;)
2. Replace every instance of `set(CMAKE_CXX_FLAGS "... ${CMAKE_CXX_FLAGS}")` with target-based compile flags.  This would be achieved via an interface library (`tbb_interface`), but each of `tbb`, `tbb_static`, etc, will link _privately_ with `tbb_interace` so that parent projects do not inherit TBB specific build flags.

Would you like a PR with this?

### PR DESCRIPTION
**Pull request by jschueller**
Closes #50

### CODE REVIEW

**Comment by wjakob** [comment]
Let me know if this is ready to merge, the change looks good to me.

**Comment by jschueller** [comment]
@wjakob it's ready

**Comment by wjakob** [comment]
Thanks!

**Comment by wjakob** [comment]
This seems to have broken the travis build (timeout), I restarted it to give it another try: https://travis-ci.org/github/wjakob/tbb/jobs/709143220

**Comment by wjakob** [comment]
Now it passed..

**Pull request merged**
